# Generated by Django 3.2.5 on 2021-07-05 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('idcontato', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('fone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuario.usuario')),
            ],
        ),
    ]
