# Generated by Django 3.2.5 on 2021-07-03 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('idcontato', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('fone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('idcompromisso', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=300)),
                ('local', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('idcontato', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.contato')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.usuario')),
            ],
        ),
    ]
